### ISSUE TITLE
Sorting filenames

### ISSUE THREAD

**Issue by kimmotikka** [smerckel/dbdreader#29] opened 2024-10-11 06:32 UTC
In DBDList:
```
class DBDList(list):

    ''' List that properly sorts dbd files.

    Object subclassed from list. The sort method defaults to sorting dbd
    files and friends in the right order.

    Parameters
    ----------
    *p : variable length list of str
        filenames
    '''
    REGEX = re.compile(r"-[0-9]*-[0-9]*-[0-9]*-[0-9]*\.[demnstDEMNST][bB][dD]")
    
    def __init__(self,*p):
        list.__init__(self,*p)

    def _keyFilename(self, key):
        match = DBDList.REGEX.search(key)
        if match and len(match.group())>=13: # minimal format: -xxxx-x-x.yyy
            s, extension = os.path.splitext(match.group())
            number_fields = s.split("-")
            n=sum([int(i)*10**j for i,j in zip(number_fields[1:],[8,5,3,0])]) # first field is '', so skip over
            r = f"{key[:match.span()[0]]}-{n}{extension.lower()}"
        else:
            r = key.lower()
        return r
    
    def sort(self,cmp=None, key=None, reverse=False):
        ''' sorts filenames ensuring dbd files are in chronological order in place

        Parameters
        ----------
        cmp :
            ingored keyword (for compatibility reasons only)
        key :
            ignored keyword (for compatibility reasons only)
        reverse : bool
            If True, performs a reverse sort.
        '''
        list.sort(self, key=self._keyFilename, reverse=reverse)

```
There are two issues: 
1) the format "# minimal format: -xxxx-x-x.yyy" should be "# minimal format: -xxxx-x-x-x.yyy" 
2) the code does not sort files correctly, as in my example with 
```
filenames = ps.select(pattern="koskelo-2024-*.[de]bd", from_date="26 9 2024 12:00")
DBDList(filenames)
```
I got:
`[..., 'koskelo-2024-280-16-0.dbd', 'koskelo-2024-280-16-0.ebd',  'koskelo-2024-269-3-3.dbd',  'koskelo-2024-269-3-3.ebd',...]
`
This may perhaps affect codes using dbdreader like pyglider.
Regards, Kimmo

**Comment by smerckel** [comment] 2024-10-11 08:16
Thanks @kimmotikka for reporting this. With respect to 

the format "# minimal format: -xxxx-x-x.yyy" should be "# minimal format: -xxxx-x-x-x.yyy"

This should have been fixed in version 0.5.6, and would mess up files written in more than one year. I cannot reproduce the behaviour you describe.

`import dbdreader
ps = dbdreader.DBDPatternSelect()
filenames = ps.select("koskelo-2024-*.[de]bd", from_date="26 9 2024")
print(filenames)`

ps.select() should return a DBDList() object, and have called .sort() on that object already. There is no need to put filenames in another DBDList. If you do, you need to call .sort() method. Could this explain your behaviour?

**Comment by kimmotikka** [comment] 2024-10-12 08:32
I had 0.5.7 and pulled the newest version. The sorting works now. 
On dbdreader.py on row 366:
`        if match and len(match.group())>=13: # minimal format: -xxxx-x-x.yyy`
Shouldn't in here be 15?

**Comment by smerckel** [comment] 2024-10-23 14:26
@kimmotikka , yes, it should. However, the test on the length is removed, because a more precise use of the regular expression makes this test redundant. Thank you for spotting this.

**Closed by smerckel** 2024-10-23 14:26 UTC
